import Head from "next/head";

import styles from "@/styles/Home.module.css";
import { DashboardMain, MainSection, Navbar } from "@/components";

const Dashboard = () => {
  return (
    <>
      <Head>
        <title>Dashboard | Dietition Dashboard | Diet Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <Navbar />
        <MainSection>
          <DashboardMain />
        </MainSection>
      </main>
    </>
  );
};

export default Dashboard;
