import { MainSection, Navbar } from "@/components";
import type { NextPage } from "next";
import Head from "next/head";

import ResourcesMain from "@/components/Resources";

const Resources: NextPage = () => {
  return (
    <>
      <Head>
        <title>Resources | Dietition Dashboard | Diet Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-full">
        <Navbar />
        <MainSection>
          <ResourcesMain />
          <div className="flex flex-col gap-3 h-96 w-full" />
        </MainSection>
      </main>
    </>
  );
};

export default Resources;
